### ISSUE TITLE
src/utils.js line 48 callback(null, body) is backwards

### ISSUE THREAD

**Issue by codecub** [jesusprubio/node-shodan-client#9]
The callback `callback(null,body)` sends the data as null and the data in the error code, which is only O.K if your callback is backwards (err, data) but the usual convention is (data, err).

I found this bug while trying to do a basic search and it said I had an error, but all my data was in the error parameter.

**Comment by jesusprubio** [comment]
First of all thanks for the feedback, as this other user comment the README included a bug. We're supposing to follow the Error-first callback, so the error is always first. :)

https://github.com/jesusprubio/node-shodan-client/issues/10
